### PR TITLE
List Item as anchor with hovered and focused

### PR DESCRIPTION
**Pull request by zecakeh**
Allows us to have a proper web experience with List Items: URL shows on hover, background color changes on hover and focus. Supports also external links that will open in a new window.

We just lose the Ripple effect on web.

Tested on web Firefox Linux
Tested on native Android

### CODE REVIEW

**Comment by tasn** [comment]
Doesn't react-naviggation have a declerative link component nowaday?

**Comment by zecakeh** [comment]
Yes, but if we use it we lose the TouchableRipple visual effects

**Comment by zecakeh** [comment]
I had forgotten to take into account if the ListItem is not an anchor (i.e. a button most likely), it is now fixed.

**Comment by tasn** [comment]
Sorry, I thought I made this comment already, but I guess I made it only in the chat! I think we should use CSS for these things on the web. That's the correct way of doing it, and it's only relevant on the web anyway. Was there a reason why not?

**Comment by zecakeh** [comment]
When we discussed it, the conclusion was that there's no easy way to style pseudo-classes without CSS-in-JS libraries. But actually CSS Modules seems like a good option (why didn't I find that earlier?)

**Comment by zecakeh** [comment]
Actually CSS Modules need some config so for now I've settled for plain css. Ready for review/merge

**Comment by tasn** [comment]
I was going to say, you can just use actual CSS, that's what I meant. :)
Reviewing now...

**Comment by tasn** [comment]
There are still conflicts, so please fix them (maybe because of my other merges?), though looks fine otherwise!

**Comment by zecakeh** [comment]
Rebased and ready to merge

**Pull request merged**
