### PR TITLE
Add a header action to search through notes

### LINKED ISSUE #8: Feature request: Search notes
Hi Tom,

You didn't mention searching notes in the "roadmap" of features you are planning.

### PR DESCRIPTION
**Pull request by zecakeh**
With fuzzy search as requested!
The results are sorted according to how close they are to the search terms and the matches are highlighted.

Screenshot_2021-01-23-12-49-03-651

This fixes #8.

Tested on web Firefox Linux
Tested on native Android

### CODE REVIEW

**Comment by zecakeh** [comment]
I'm actually going to integrate it to the NoteListScreen. It's the default search behavior of Material Design and it'll be easier to handle in Split View.

**Comment by tasn** [comment]
Ahhhhh, so cool!!!

Let me know when it's ready to merge...

**Comment by zecakeh** [comment]
Okay, now it's ready for review.

**Comment by tasn** [comment]
Looks good to me, though why in the toolbar (which you now also want to use for switching collections), why not its own page? Because I assume this searches everything and not just the notes in the current view (or does it?).

Do the new deps add any binary deps, or just JS?

**Comment by zecakeh** [comment]
I just used the recommended behavior in Material Design. On mobile apps I guess it's easier to search notes with some text than into a hierarchy, that's why search has to be readily available.
Right now it searches through all notes, I was actually wondering if it should only search inside the open notebook.

All the new dependencies are pure JS.

**Comment by tasn** [comment]
OK, great. So fix conflicts and this can go in.

**Comment by zecakeh** [comment]
Rebased and ready to merge

**Comment by tasn** [comment]
Still conflicts (I guess because of my other merges).

**Comment by zecakeh** [comment]
I'm gonna wait until you merge #142 because I know there's gonna be merge conflicts again.

**Comment by tasn** [comment]
Done.

**Comment by zecakeh** [comment]
Rebased (and uses the brand new `ListItem`) and ready to merge

**Comment by Zahrun** [comment]
@tasn @zecakeh 
Thank you for implementing search in etesync notes.
However, I have been missing and looking for this feature on Android. Since the latest available build is 1.7.0 from 2021, before this PR was merged, search is still not available to etesync notes android users. Could you please make a new release?
Thank you again

**Pull request merged**
