### PR TITLE
Export Link and Clickable components from ListItem

### PR DESCRIPTION
**Pull request by zecakeh**
Allows us to reuse the behavior with other components than List.Item.

Tested on web Firefox Linux
Tested on native Android

### CODE REVIEW

**Comment by tasn** [comment]
Looks fine, though one thing: the convention for `child` is to call it `render` if memory serves.

**Comment by zecakeh** [comment]
Maybe `renderChild` to make it clear it's not the rendering of the whole component?

**Comment by tasn** [comment]
Ok

**Comment by zecakeh** [comment]
Modified and ready to merge

**Pull request merged**
