### PR TITLE
Update CachedItems after collectionUpload

### PR DESCRIPTION
**Pull request by zecakeh**
That way we don't have to use SyncManager with performSync afterwards.

Tested on web Firefox Linux
Tested on native Android

### CODE REVIEW

**Comment by tasn** [comment]
Hero! I assume you tested it properly with adding collections and then trying to navigate to the collection page and etc?

**Comment by zecakeh** [comment]
Yep! I also looked if it was syncing the changes with other devices.

**Comment by zecakeh** [comment]
But I forgot to clean up imports 😅

**Comment by zecakeh** [comment]
Now it's ready.

**Pull request merged**
