### PR TITLE
Fix Appbar if title is a function

### PR DESCRIPTION
**Pull request by zecakeh**
Tested on web Firefox Linux
Tested on native Android

### CODE REVIEW

**Comment by tasn** [comment]
Is it ever a function in our code?

**Comment by zecakeh** [comment]
I'm working on the new notebooks list and I'm making the title a button to open the notebooks list, so I need it.

**Comment by tasn** [comment]
As indicated on IRC, I'm not a huge fan of this idea. I don't think a drop-drown from the title is the right way of doing collection changing...

**Comment by zecakeh** [comment]
I'm not working on the dropdown, I'm working on a bottom sheet, but that's how I trigger it.

**Comment by tasn** [comment]
I'm not sure I follow what this is. Could you maybe open a ticket with a proposal + screenshots or something that we can discuss?

**Comment by zecakeh** [comment]
That's what I was about to do after this PR was merged. According to the types, `headerTitle` can receive a function so it is kind of a general fix. I just encountered the issue while working on that other stuff.

**Pull request merged**
